# Generated by Django 3.1.7 on 2021-03-28 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210328_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-name', '-code'], 'verbose_name': 'product'},
        ),
    ]
